
- name: Install anyenv
  git:
    repo: git://github.com/riywo/anyenv.git
    dest: "{{ anyenv_root }}"
  register: ret

- name: Setting environment
  template:
    src: anyenv.sh.j2
    dest: /etc/profile.d/anyenv.sh

- name: Initialize anyenv
  command: bash -lc "anyenv version"
  when: ret.changed
