
- name: Check php install
  command: bash -lc "phpenv versions --bare"
  ignore_errors: yes
  register: ret
  changed_when: false

- name: Install php
  command: bash -lc "phpenv install {{ phpinfo.version }}"
  when: "'{{ phpinfo.version }}' not in ret.stdout_lines"

- name: Set global php version
  command: bash -lc "phpenv global {{ phpinfo.version }}"
  changed_when: false

- name: Rehash phpenv
  command: bash -lc "phpenv rehash"
  changed_when: false

- name: Install pear packages
  pear:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ phpenv_root }}/shims/pear"
  with_items: "{{ phpinfo.packages | default([]) }}"

- name: Restore global version
  command: bash -lc "phpenv global {{ before_global_version.stdout }}"
  changed_when: false

- name: Rehash phpenv
  command: bash -lc "phpenv rehash"
  changed_when: false

