
- name: add repo
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ xenial nginx
    filename: nginx
    codename: xenial

- name: add src repo
  apt_repository:
    repo: deb-src http://nginx.org/packages/ubuntu/ xenial nginx
    filename: nginx
    codename: xenial

- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
    allow_unauthenticated: yes

- name: Create service.d folder
  file:
    path: /etc/systemd/system/nginx.service.d/
    state: directory

- name: Copy limits.conf 
  copy:
    src: limits.conf
    dest: /etc/systemd/system/nginx.service.d/limits.conf
  register: ret_svc

- name: Delete default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Reload nginx

- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Reload nginx

- name: Copy www.conf
  template:
    src: www.conf
    dest: /etc/nginx/conf.d/www.conf
  notify: Reload nginx

  # TODO: Modify please!!
- name: Download alp
  unarchive:
    src: https://github.com/tkuchiki/alp/releases/download/v0.3.1/alp_linux_amd64.zip
    dest: /tmp

- name: Start and Enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: "{{ ret_svc | changed }}"
