limits_param:
  - domain: "*"
    type: soft
    item: nofile
    value: 1006500
  - domain: "*"
    type: hard
    item: nofile
    value: 1006500
  - domain: "*"
    type: soft
    item: nproc value: 65536
    dest: /etc/security/limits.d/20-nproc.conf
  - domain: "*"
    type: hard
    item: nproc
    value: 65536
    dest: /etc/security/limits.d/20-nproc.conf

systemd_default_limits_param:
  nofile: 1006500
  nproc: 65536

sysctl_param:
  - name: kernel.threads-max
    value: 1006500
  - name: kernel.pid_max
    value: 65536
  - name: kernel.ftrace_enabled
    value: 0
  - name: kernel.watchdog
    value: 0
  - name: kernel.soft_watchdog
    value: 0
  - name: kernel.sched_migration_cost_ns
    value: 5000000
  - name: kernel.sched_min_granularity_ns
    value: 10000000
  - name: kernel.sched_wakeup_granularity_ns
    value: 15000000
  - name: net.core.busy_poll
    value: 50
  - name: vm.overcommit_memory
    value: 0
  - name: vm.overcommit_ratio
    value: 50
  - name: vm.swappiness
    value: 5
  - name: vm.dirty_ratio
    value: 40
  - name: vm.dirty_background_ratio
    value: 10
  - name: net.core.busy_read
    value: 50
  - name: net.core.busy_poll
    value: 50
  - name: net.ipv4.ip_local_port_range
    value: 12000 65535
  - name: net.ipv4.tcp_max_syn_backlog
    value: 32768
  - name: net.ipv4.tcp_rmem
    value: 1529184 2038912 3058368
  - name: net.ipv4.udp_mem
    value: 3145728 4194304 16777216
  - name: net.ipv4.tcp_wmem
    value: 1529184 2038912 3058368
  - name: net.ipv4.tcp_fastopen
    value: 3
  - name: net.ipv4.tcp_window_scaling
    value: 1
  - name: net.ipv4.tcp_tw_reuse
    value: 1
  - name: net.ipv4.tcp_tw_recycle
    value: 1
  - name: net.ipv4.tcp_slow_start_after_idle
    value: 0
  - name: net.ipv4.tcp_timestamps
    value: 0
  - name: net.ipv4.tcp_keepalive_time
    value: 10
  - name: net.ipv4.tcp_keepalive_probes
    value: 2
  - name: net.ipv4.tcp_keepalive_intvl
    value: 3
  - name: net.core.netdev_max_backlog
    value: 32768
  - name: net.core.somaxconn
    value: 65535

apt_install_pkg:
  - sysstat
  - jq
  - zsh
  - htop
  - wget
  - socat
  - dstat
  - strace
  - silversearcher-ag
  - numactl
  - numad
  - unzip
